### ISSUE TITLE
Allow replace directives only with an explanation

### ISSUE THREAD

**Issue by mx-psi** [ldez/gomoddirectives#1]
Similar to the current behavior for `retract` directives it would be useful to have a check to deny the use of `replace` directives without an explanation.

This would be a bit harder to implement than the `retract`directive but it seems doable (check for presence of a comment just before each replace statement/block on the `Stmnt` list provided by `modfile`)

**Comment by ldez** [comment]
The `golang.org/x/mod/modfile` API doesn't provide something to handle a comment for `require`.

https://pkg.go.dev/golang.org/x/mod@v0.4.2/modfile#Require
https://pkg.go.dev/golang.org/x/mod@v0.4.2/modfile#Replace

Also, there are several possibilities for comment for this directive:
```
# explanation
replace foo => bar

replace foo => bar # explanation

# explanation
replace (
	replace foo => bar
	replace fii => bir 
)
```

And those comments can be move or deleted by the go command.

The option `ReplaceAllowList` is here to handle the case of authorized `replace`.
