### ISSUE TITLE
Commented out directives trigger linter error

### ISSUE THREAD

**Issue by mixedCase** [ldez/gomoddirectives#4]
I just had a go.mod directive of the form:

```
// replace github.com/owner/repo => /home/mixedcase/code/owner/repo
```

trigger an error.

Apologies if this is a golangci-lint error or misuse, but from what I've been able to understand this should not trigger the warning.

**Comment by ldez** [comment]
Hello,

I'm not able to reproduce this, can you provide your full `go.mod` file and the logs?

**Comment by mixedCase** [comment]
Unfortunately I can't share the full go.mod that causes the issue for legal reasons and I am failing to reproduce the issue with a smaller example.

This is what appears, with repo name changed:

```
go.mod:5:1: local replacement are not allowed: github.com/owner/dep (gomoddirectives)
// replace github.com/owner/dep => /home/mixedcase/code/owner/dep
```

The offending go.mod contains 98 lines, is composed of three different require blocks, first with 29 dependencies, second with 16 dependencies and third with 39 dependencies. Go version is set to 1.19, the module name line is akin to `module github.com/owner/repo`. The mentioned commented out replace is the only forbidden directive there.

I am using golangci-lint version 1.50.1 obtained from nixpkgs on NixOS. gomoddirectives is using its default configuration.

Please do close the issue if being unable to provide a reproducer is a deal-breaker, I certainly understand. In any case, anything else I could try or information I could provide please let me know.

**Comment by ldez** [comment]
I tried on several projects (go.mod with 363 lines, with 135 lines, with only 10 lines) and I'm not able to reproduce your problem.

Without a reproducer I'm not able to diagnose.

FYI, the go.mod parsing is the same as Go.

**Comment by mixedCase** [comment]
Got it, can't explain what's going on. Go is certainly picking the right package with the thing commented out and with it on. Closing as a freak accident.
